# Copyright 2023-2024 The MathWorks, Inc.
# Build & Publish matlab/ubuntu20.04/Dockerfile.byoi
name: matlab/ubuntu20.04/Dockerfile.byoi

# Define when builds will occur:
on:
  # Run workflow when there is a push to the 'main' branch & push includes changes to any files in described path
  push:
    branches:
      - 'main'
    paths:
      - 'matlab/ubuntu20.04/Dockerfile.byoi'

  # Run at 00:00 on every Monday (1st Day of the Week) (See: crontab.guru)
  schedule:
    - cron: '0 0 * * 1'

  workflow_dispatch:

jobs:
  build-and-publish-docker-image:
    strategy:
      fail-fast: false
      matrix:
        matlab_release_tag: [r2024b, r2024a, r2023b, r2023a, r2022b, r2022a, r2021b, r2021a, r2020b]
    uses: ./.github/workflows/build-and-publish-docker-image.yml
    secrets: inherit
    with:
        docker_build_context: './matlab/ubuntu20.04'
        base_image_name: ghcr.io/${{ github.repository }}/jupyter-byoi-matlab-notebook
        os_info_tag: 'ubuntu20.04'
        matlab_release_tag: ${{ matrix.matlab_release_tag }}
        is_default_os: false
